# Generated by Django 6.0 on 2026-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.AddField(
            model_name='organization',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_np',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='organization/organization/banner'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_en',
            field=models.TextField(default='dddd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='description_np',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/organization/logo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manifesto_document',
            field=models.FileField(blank=True, null=True, upload_to='org_manifestos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manifesto_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='manifesto_np',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(default='dddd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='name_np',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='dd', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
    ]
