# Generated by Django 6.0 on 2026-01-19 11:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0002_remove_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manifesto_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manifesto_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
