# Generated by Django 6.0 on 2026-01-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0003_alter_branch_address_alter_organization_address_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branch'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='staffrole',
            options={'verbose_name': 'Staff Role', 'verbose_name_plural': 'Staff Role'},
        ),
    ]
