# Generated by Django 6.0 on 2026-01-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='membership_type',
            field=models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('donor', 'Donor')], default='member', max_length=20, verbose_name='Membership Type'),
        ),
    ]
