# Generated by Django 6.0 on 2026-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignactivity',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Enter the end time of the event (HH:MM or HH:MM:SS).', null=True),
        ),
        migrations.AlterField(
            model_name='campaignactivity',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Enter the start time of the event (HH:MM or HH:MM:SS).', null=True),
        ),
    ]
