# Generated by Django 6.0 on 2026-01-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_active',
        ),
    ]
