# Generated by Django 6.0 on 2026-01-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_campaign_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='is_active',
        ),
    ]
