# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaign_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_date'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaign'},
        ),
        migrations.AlterModelOptions(
            name='campaignactivity',
            options={'ordering': ['-date'], 'verbose_name': 'Campaign Activity', 'verbose_name_plural': 'Campaign Activity'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteer'},
        ),
    ]
