# Generated by Django 6.0 on 2026-01-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('position_en', models.CharField(max_length=255)),
                ('position_np', models.CharField(blank=True, max_length=255, null=True)),
                ('member_type', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member'), ('advisor', 'Advisor')], default='member', max_length=20)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_np', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'members',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description_en', models.TextField()),
                ('description_np', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/organization/logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='organization/organization/banner')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('manifesto_en', models.TextField(blank=True, null=True)),
                ('manifesto_np', models.TextField(blank=True, null=True)),
                ('manifesto_document', models.FileField(blank=True, null=True, upload_to='org_manifestos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_en', models.TextField(blank=True, null=True)),
                ('address_np', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
    ]
