# Generated by Django 6.0 on 2026-01-11 17:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('position_en', models.CharField(max_length=255)),
                ('position_np', models.CharField(blank=True, max_length=255, null=True)),
                ('member_type', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member'), ('advisor', 'Advisor')], default='member', max_length=20)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_np', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'members',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description_en', models.TextField()),
                ('description_np', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/organization/logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='organization/organization/banner')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('manifesto_en', models.TextField(blank=True, null=True)),
                ('manifesto_np', models.TextField(blank=True, null=True)),
                ('manifesto_document', models.FileField(blank=True, null=True, upload_to='org_manifestos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_en', models.TextField(blank=True, null=True)),
                ('address_np', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ne', models.CharField(blank=True, max_length=255, verbose_name='Title (Nepali)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('description_ne', models.TextField(blank=True, verbose_name='Description (Nepali)')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or path', max_length=100)),
                ('category', models.CharField(choices=[('governance', 'Transparent Governance'), ('economy', 'Sustainable Economy'), ('environment', 'Environment/Infrastructure'), ('society', 'Inclusive Society'), ('digital', 'Digital Governance')], max_length=50)),
                ('content', models.TextField(blank=True, help_text='Detailed policy content')),
                ('content_ne', models.TextField(blank=True, verbose_name='Content (Nepali)')),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional donor message')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('donor', 'Donor')], max_length=20, verbose_name='Membership Type')),
                ('first_name', models.CharField(help_text="User's first name", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="User's last name", max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(help_text="Father's full name", max_length=100, verbose_name="Father's Name")),
                ('date_of_birth', models.DateField(help_text='Birth date in format MM/DD/YYYY', verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, verbose_name='Email Address')),
                ('province', models.CharField(choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpashchim', 'Sudurpashchim')], max_length=20, verbose_name='Province')),
                ('district', models.CharField(help_text='District name', max_length=100, verbose_name='District')),
                ('municipality', models.CharField(help_text='Municipality or Rural Municipality name', max_length=150, verbose_name='Municipality/Rural Municipality')),
                ('ward_number', models.CharField(help_text='Ward number', max_length=10, verbose_name='Ward Number')),
                ('village_settlement', models.CharField(blank=True, help_text='Village or Settlement name (optional)', max_length=100, null=True, verbose_name='Village/Settlement')),
                ('address', models.CharField(help_text='Complete address', max_length=500, verbose_name='Full Address')),
                ('citizenship_number', models.CharField(help_text='National citizenship ID number', max_length=50, verbose_name='Citizenship Number')),
                ('passport_photo', models.ImageField(help_text='Upload passport size photo (JPG, PNG or GIF, max 2MB)', upload_to='memberships/passport_photos/%Y/%m/', verbose_name='Passport Size Photo')),
                ('citizenship_copy', models.FileField(help_text='Upload citizenship document copy (PDF or Image, max 5MB)', upload_to='memberships/citizenship_docs/%Y/%m/', verbose_name='Citizenship Copy')),
                ('occupation', models.CharField(blank=True, help_text='Current occupation or profession', max_length=100, verbose_name='Occupation')),
                ('motivation', models.TextField(help_text='Why do you want to join? What are your motivations?', verbose_name='Motivation')),
                ('terms_accepted', models.BooleanField(default=False, help_text='I accept the terms and conditions', verbose_name='Terms Accepted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
            ],
            options={
                'verbose_name': 'Membership Registration',
                'verbose_name_plural': 'Membership Registrations',
                'db_table': 'membership_registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='membership__status_2df59f_idx'), models.Index(fields=['membership_type', 'status'], name='membership__members_921581_idx'), models.Index(fields=['province', 'district'], name='membership__provinc_f900e3_idx')],
            },
        ),
    ]
