# Generated by Django 6.0 on 2026-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipregistration',
            name='motivation',
            field=models.TextField(blank=True, help_text='Why do you want to join? What are your motivations?', null=True, verbose_name='Motivation'),
        ),
    ]
