# Generated by Django 6.0 on 2026-01-05 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ne', models.CharField(blank=True, max_length=255, verbose_name='Title (Nepali)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('description_ne', models.TextField(blank=True, verbose_name='Description (Nepali)')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or path', max_length=100)),
                ('category', models.CharField(choices=[('governance', 'Transparent Governance'), ('economy', 'Sustainable Economy'), ('environment', 'Environment/Infrastructure'), ('society', 'Inclusive Society'), ('digital', 'Digital Governance')], max_length=50)),
                ('content', models.TextField(blank=True, help_text='Detailed policy content')),
                ('content_ne', models.TextField(blank=True, verbose_name='Content (Nepali)')),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='Leadership',
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional donor message')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('donor', 'Donor')], max_length=20)),
                ('province', models.CharField(choices=[('koshi', 'Koshi'), ('gandaki', 'Gandaki'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('lumbini', 'Lumbini'), ('sudurpashchim', 'Sudurpashchim'), ('karnali', 'Karnali')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('motivation', models.TextField(help_text='Why do you want to join?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Registration',
                'verbose_name_plural': 'Membership Registrations',
                'db_table': 'membership_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
