# Generated by Django 6.0 on 2026-01-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipregistration',
            name='user',
        ),
    ]
