# Generated by Django 6.0 on 2026-01-13 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_membershipregistration_motivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ne', models.CharField(blank=True, max_length=100, verbose_name='Name (Nepali)')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or image path', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Category',
                'verbose_name_plural': 'Policy Categories',
                'db_table': 'policy_categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='organization.policycategory'),
        ),
    ]
