# Generated by Django 6.0 on 2026-01-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_policycategory_alter_policy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipregistration',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='membershipregistration',
            old_name='last_name',
            new_name='mother_name',
        ),
    ]
