# Generated by Django 6.0 on 2026-01-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_first_name_membershipregistration_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipregistration',
            name='occupation',
            field=models.CharField(blank=True, help_text='Current occupation or profession', max_length=100, null=True, verbose_name='Occupation'),
        ),
    ]
