# Generated by Django 6.0 on 2026-01-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_membershipregistration_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipregistration',
            name='full_name',
            field=models.CharField(help_text="User's full name", max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='membershipregistration',
            name='mother_name',
            field=models.CharField(help_text="Mother's full name", max_length=100, verbose_name="Mother's Name"),
        ),
    ]
