# Generated by Django 6.0 on 2026-01-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_membershipregistration_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membershipregistration',
            name='membership__members_921581_idx',
        ),
        migrations.RemoveField(
            model_name='membershipregistration',
            name='membership_type',
        ),
    ]
