# Generated by Django 6.0 on 2026-01-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_membershipregistration_membership__members_921581_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
