# Generated by Django 6.0 on 2026-01-19 11:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional donor message', null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipregistration',
            name='motivation',
            field=tinymce.models.HTMLField(blank=True, help_text='Why do you want to join? What are your motivations?', null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='membershipregistration',
            name='rejection_reason',
            field=tinymce.models.HTMLField(blank=True, help_text='Reason for rejection (if applicable)', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Detailed policy content', null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content_ne',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content (Nepali)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description_ne',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description (Nepali)'),
        ),
    ]
