# Generated by Django 6.0 on 2026-01-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_donation_message_alter_leadership_bio_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donation'},
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'ordering': ['order', 'name_en'], 'verbose_name': 'Leadership', 'verbose_name_plural': 'Leadership'},
        ),
        migrations.AlterModelOptions(
            name='membershipregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Membership Registration', 'verbose_name_plural': 'Membership Registration'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Policy', 'verbose_name_plural': 'Policy'},
        ),
        migrations.AlterModelOptions(
            name='policycategory',
            options={'ordering': ['order', 'name_en'], 'verbose_name': 'Policy Category', 'verbose_name_plural': 'Policy Category'},
        ),
    ]
