# Generated by Django 6.0 on 2026-01-19 11:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futurevision',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
