# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_about_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'About Image', 'verbose_name_plural': 'About Image'},
        ),
        migrations.AlterModelOptions(
            name='futurevision',
            options={'ordering': ['-created_at'], 'verbose_name': 'Future Vision', 'verbose_name_plural': 'Future Vision'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['order'], 'verbose_name': 'Social Media Link', 'verbose_name_plural': 'Social Media Link'},
        ),
    ]
