# Generated by Django 6.0 on 2026-01-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_about_options_alter_aboutimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='FontAwesome / icon class (e.g. fa-brands fa-facebook)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Platform',
                'verbose_name_plural': 'Social Platforms',
                'db_table': 'social_platforms',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['order'], 'verbose_name': 'Social Media Link', 'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='icon',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='website.socialplatform'),
        ),
    ]
