# Generated by Django 6.0 on 2026-01-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_socialplatform_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='website.socialplatform'),
        ),
    ]
