# Generated by Django 6.0 on 2026-01-21 06:16

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero News',
                'verbose_name_plural': 'Hero News',
                'db_table': 'hero_news',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['order'], 'verbose_name': 'Social Platform', 'verbose_name_plural': 'Social Platform'},
        ),
        migrations.AlterModelOptions(
            name='socialplatform',
            options={'ordering': ['order'], 'verbose_name': 'Social Platform Icon', 'verbose_name_plural': 'Social Platform Icon'},
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_url', models.URLField(blank=True)),
                ('main_image', models.ImageField(upload_to='hero_section/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.heronews')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'db_table': 'hero_section',
                'ordering': ['-created_at'],
            },
        ),
    ]
