# Generated by Django 6.0 on 2026-01-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_heronews_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heronews',
            options={},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={},
        ),
        migrations.RemoveField(
            model_name='heronews',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='hero_news',
        ),
        migrations.AddField(
            model_name='heronews',
            name='hero_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_news', to='website.herosection'),
        ),
        migrations.AlterModelTable(
            name='heronews',
            table=None,
        ),
        migrations.AlterModelTable(
            name='herosection',
            table=None,
        ),
    ]
