# Generated by Django 6.0 on 2026-01-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_heronews_options_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heronews',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='heronews',
            name='title',
        ),
    ]
