# Generated by Django 6.0 on 2026-01-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_heronews_subtitle_remove_heronews_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heronews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hero News', 'verbose_name_plural': 'Hero News'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.AlterModelTable(
            name='heronews',
            table='hero_news',
        ),
        migrations.AlterModelTable(
            name='herosection',
            table='hero_section',
        ),
    ]
