# Generated by Django 6.0 on 2026-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_heronews_options_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_section/'),
        ),
    ]
