# Generated by Django 6.0 on 2026-01-21 08:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_herosection_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heronews',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='button_text',
            new_name='button_text_en',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='subtitle',
            new_name='button_text_np',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='heronews',
            name='description_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_np',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_np',
            field=models.CharField(default='ss', max_length=255),
            preserve_default=False,
        ),
    ]
