# Generated by Django 6.0 on 2026-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_description_heronews_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='main_image',
        ),
        migrations.AddField(
            model_name='heronews',
            name='title_en',
            field=models.CharField(default='222', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heronews',
            name='title_np',
            field=models.CharField(default='dddsdfsfs', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_section/background_image'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_section/profile_image'),
        ),
    ]
