# Generated by Django 6.0 on 2026-01-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('blog_view', 'Blog View'), ('campaign_view', 'Campaign View'), ('download', 'Download'), ('form_submit', 'Form Submit')], max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField()),
                ('referrer', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['object_type', 'object_id'], name='analytics_e_object__35a664_idx')],
            },
        ),
    ]
