# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsevent_referrer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analytics Event', 'verbose_name_plural': 'Analytics Event'},
        ),
    ]
