# Generated by Django 6.0 on 2026-01-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('content', models.TextField(help_text='Main page content (HTML allowed)')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary of the page', max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('seo_title', models.CharField(blank=True, help_text='Custom title for search engines', max_length=70)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
