# Generated by Django 6.0 on 2026-01-19 11:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Main page content (HTML allowed)', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, help_text='Short summary of the page', max_length=300, null=True),
        ),
    ]
