# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_content_alter_page_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Page'},
        ),
    ]
