# Generated by Django 6.0 on 2026-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description_en', models.TextField()),
                ('description_np', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or image', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/service/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
