# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Service'},
        ),
    ]
