# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Category'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'Blog Tag', 'verbose_name_plural': 'Blog Tag'},
        ),
    ]
