# Generated by Django 6.0 on 2026-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_content_en_alter_blog_content_np_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_np',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt_np',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description_np',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
