# Generated by Django 6.0 on 2026-01-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_content_en_alter_blog_content_np_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Category'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name_plural': 'Blog Tag'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment'},
        ),
    ]
