# Generated by Django 6.0 on 2026-01-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization_app.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization_app.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('gandaki', 'Gandaki'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('lumbini', 'Lumbini'), ('sudurpashchim', 'Sudurpashchim'), ('karnali', 'Karnali')], max_length=20, null=True),
        ),
    ]
