# Generated by Django 6.0 on 2026-01-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, help_text='Month (1-12)', null=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('description_np', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='timelines/timeline/')),
                ('is_milestone', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timeline',
                'ordering': ['-year', '-month', 'order'],
            },
        ),
    ]
