# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_alter_timeline_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-year', '-month', 'order'], 'verbose_name': 'Timeline', 'verbose_name_plural': 'Timeline'},
        ),
    ]
