# Generated by Django 6.0 on 2026-01-19 11:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Short description of the manifesto'),
        ),
    ]
