# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0002_alter_manifesto_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifesto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Manifesto', 'verbose_name_plural': 'Manifesto'},
        ),
    ]
