# Generated by Django 6.0 on 2026-01-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
