# Generated by Django 6.0 on 2026-01-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_sub_title_menuitem_title'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Select a page OR enter a custom URL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.page'),
        ),
    ]
