# Generated by Django 6.0 on 2026-01-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Check if this item is an external link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Auto fill page url OR enter a custom URL', max_length=255, null=True),
        ),
    ]
