# Generated by Django 6.0 on 2026-01-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description_en', models.TextField(blank=True, null=True)),
                ('meta_description_np', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('og_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description_en', models.TextField(blank=True, null=True)),
                ('og_description_np', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/seometadata/')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots', models.CharField(default='index,follow', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'seo_metadata',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_metadat_content_600398_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
