# Generated by Django 6.0 on 2026-01-19 11:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometadata',
            name='keywords',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='meta_description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='meta_description_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='og_description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='og_description_np',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
