# Generated by Django 6.0 on 2026-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_seometadata_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seometadata',
            options={'verbose_name': 'SEO Metadata', 'verbose_name_plural': 'SEO Metadata'},
        ),
    ]
